#!/usr/bin/env python3
"""Assemble static app data from canonical questions and verified English shards.

Defaults are relative to this script, not the working directory. Draft shards are
ignored unless --allow-drafts is explicit; final records then override drafts.
Validation and serialization finish before either output is touched. Both files
are staged before replacement, but two atomic replaces are NOT a transaction.
"""
import argparse
import copy
import json
import os
from pathlib import Path
import sys
import tempfile

PIPE = Path(__file__).resolve().parent
APP = PIPE.parent / "app"
COUNTS = {"general": 300, "berlin": 10, "total": 310}
ENGLISH_FIELDS = ("question_en", "asking_note", "answer_explanation")
JS_HEADER = "/* generated by build_questions.py — do not edit by hand */\n"


def require(condition, message):
    if not condition:
        raise ValueError(message)


def nonempty(value):
    return isinstance(value, str) and bool(value.strip())


def valid_id(value):
    return type(value) is int and 1 <= value <= COUNTS["total"]


def load_core(path=PIPE / "questions.core.json"):
    with Path(path).open(encoding="utf-8") as source:
        return json.load(source)


def validate_content(record, location):
    require(isinstance(record, dict), f"{location}: expected a content object")
    require(valid_id(record.get("id")), f"{location}: invalid content id")
    for field in ENGLISH_FIELDS:
        require(nonempty(record.get(field)), f"{location}: missing English {field}")
    options = record.get("options_en")
    require(isinstance(options, list) and len(options) == 4 and
            all(nonempty(option) for option in options),
            f"{location}: options_en must contain four nonempty strings")
    notes = record.get("distractor_notes")
    require(isinstance(notes, list) and len(notes) == 4 and
            all(isinstance(note, str) for note in notes),
            f"{location}: distractor_notes must contain four strings")


def load_content(shard_dir=PIPE / "content_shards", allow_drafts=False):
    """Reject duplicates within each tier; deliberately allow final over gen."""
    content, sources = {}, {}
    for tier in (("gen", "final") if allow_drafts else ("final",)):
        seen = set()
        for path in sorted(Path(shard_dir).glob(f"{tier}_*.json")):
            with path.open(encoding="utf-8") as source:
                records = json.load(source)
            require(isinstance(records, list), f"{path}: expected a shard array")
            for record in records:
                validate_content(record, str(path))
                qid = record["id"]
                require(qid not in seen, f"{path}: duplicate {tier} id {qid}")
                seen.add(qid)
                content[qid] = record
                sources[qid] = tier
    return content, sources


def validate_asset(reference, app_dir, location):
    require(nonempty(reference), f"{location}: invalid image path")
    relative = Path(reference)
    root = Path(app_dir).resolve()
    path = (root / relative).resolve()
    require(not relative.is_absolute() and ".." not in relative.parts and
            path.is_relative_to(root) and path.is_file(),
            f"{location}: missing or unsafe image asset {reference!r}")


def validate_payload(payload, app_dir=APP, *, english=True):
    require(isinstance(payload, dict), "core must be an object")
    counts = payload.get("counts")
    require(isinstance(counts, dict) and counts == COUNTS and
            all(type(value) is int for value in counts.values()),
            "counts must be 300 general + 10 Berlin = 310")
    questions = payload.get("questions")
    require(isinstance(questions, list) and len(questions) == COUNTS["total"],
            "expected exactly 310 questions")
    seen = set()
    for question in questions:
        require(isinstance(question, dict), "question must be an object")
        qid = question.get("id")
        require(valid_id(qid), f"invalid question id {qid!r}")
        require(qid not in seen, f"duplicate question id {qid}")
        seen.add(qid)
        label = f"id {qid}"
        pool = "general" if qid <= 300 else "berlin"
        require(question.get("category") == pool and question.get("exam_pool") == pool,
                f"{label}: wrong category/exam_pool")
        require(question.get("id_str") == (str(qid) if qid <= 300 else f"BE-{qid - 300}"),
                f"{label}: wrong id_str")
        require(nonempty(question.get("question_de")), f"{label}: missing German question")
        options = question.get("options")
        require(isinstance(options, list) and len(options) == 4 and
                all(isinstance(option, dict) for option in options),
                f"{label}: expected four option objects")
        index = question.get("correct_index")
        require(type(index) is int and 0 <= index < 4, f"{label}: bad correct_index")
        require(all(type(option.get("correct")) is bool for option in options) and
                [option["correct"] for option in options] == [i == index for i in range(4)],
                f"{label}: correct flags do not match correct_index")
        for option in options:
            require(nonempty(option.get("text_de")), f"{label}: missing German option")
        kind = question.get("image_kind")
        stem = question.get("question_image")
        images = [option.get("image") for option in options]
        require(kind in (None, "stem", "options"), f"{label}: invalid image_kind")
        require((kind == "stem" and nonempty(stem) and all(image is None for image in images)) or
                (kind == "options" and stem is None and all(nonempty(image) for image in images)) or
                (kind is None and stem is None and all(image is None for image in images)),
                f"{label}: image references do not match image_kind")
        # Archived oet_screenshot provenance is not a deployed image dependency.
        for reference in [stem, *images]:
            if reference is not None:
                validate_asset(reference, app_dir, label)
        if english:
            validate_content({**question, "options_en": [o.get("text_en") for o in options]}, label)
            notes = question["distractor_notes"]
            # Existing EU-flag image question has an explanation but no per-image
            # notes. Preserve that known content gap; never silently invent notes.
            legacy_image_notes = qid == 226 and kind == "options" and notes == [""] * 4
            require(legacy_image_notes or (notes[index] == "" and
                    all(nonempty(note) for i, note in enumerate(notes) if i != index)),
                    f"{label}: distractor notes must explain only the three wrong options")


def assemble(core, content, app_dir=APP):
    """Merge only English fields without mutating core, option order or evidence."""
    validate_payload(core, app_dir, english=False)
    require(set(content) == {q["id"] for q in core["questions"]},
            "complete English content for all 310 ids is required (verified by default)")
    questions = copy.deepcopy(core["questions"])
    for question in questions:
        record = content[question["id"]]
        validate_content(record, f"id {question['id']}")
        require(record["id"] == question["id"], "content key/id mismatch")
        for field in (*ENGLISH_FIELDS, "distractor_notes"):
            question[field] = copy.deepcopy(record[field])
        for option, text in zip(question["options"], record["options_en"]):
            option["text_en"] = text
    payload = {"version": core.get("version"), "source": core.get("source"),
               "counts": copy.deepcopy(core["counts"]), "questions": questions}
    validate_payload(payload, app_dir)
    return payload


def serialize_payload(payload):
    """Keep the original JSON spacing, key order, Unicode and JS wrapper."""
    compact = json.dumps(payload, ensure_ascii=False, allow_nan=False)
    return {
        "questions.json": json.dumps(payload, ensure_ascii=False, indent=1, allow_nan=False).encode("utf-8"),
        "questions.js": (JS_HEADER + "window.QUESTIONS = " + compact + ";\n").encode("utf-8"),
    }


def write_payload(payload, output_dir=APP / "data", app_dir=APP):
    validate_payload(payload, app_dir)
    serialized = serialize_payload(payload)  # Both encodings finish before any write.
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    staged = []
    try:
        for name, data in serialized.items():
            destination = output_dir / name
            with tempfile.NamedTemporaryFile(dir=output_dir, prefix=f".{name}.", delete=False) as temp:
                staged.append((Path(temp.name), destination))
                temp.write(data)
            os.chmod(temp.name, destination.stat().st_mode & 0o777 if destination.exists() else 0o644)
        # A crash or failure between these replaces can leave mixed generations.
        for temporary, destination in staged:
            os.replace(temporary, destination)
    finally:
        for temporary, _ in staged:
            temporary.unlink(missing_ok=True)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--core", type=Path, default=PIPE / "questions.core.json")
    parser.add_argument("--shards", type=Path, default=PIPE / "content_shards")
    parser.add_argument("--app", type=Path, default=APP, help="root for resolving image assets")
    parser.add_argument("--output", type=Path, help="output directory (default: APP/data)")
    parser.add_argument("--allow-drafts", action="store_true", help="allow gen_* fallback; final_* wins")
    args = parser.parse_args(argv)
    try:
        content, sources = load_content(args.shards, args.allow_drafts)
        payload = assemble(load_core(args.core), content, args.app)
        write_payload(payload, args.output or args.app / "data", args.app)
    except (OSError, ValueError, TypeError) as error:
        print(f"BUILD FAILED: {error}", file=sys.stderr)
        return 1
    verified = sum(source == "final" for source in sources.values())
    print(f"OK: 310 questions; {verified} verified / {len(sources)} content records; both outputs written.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
